### ISSUE TITLE
SWITCHER: Alt-tab/FI_NEXT not working

### ISSUE THREAD

**Issue by felixfung** [dreamcat4/skippy-xd#120]
Switcher works if there are no shared keys between the hot keys that launch skippy, and prev/next keys. (e.g. Control a to launch skippy, 'd' to do prev, 'f' to do next, everything works)

However, when I am trying "classic" hot keys Alt-Tab, setting up my custom hot key to launch skippy via Alt+Tab, and using Tab as keysNext. I am running into these problems due to the two keys, Alt and Tab, triggering in multiple context:

1. If I set up Alt+Tab to do `skippy-xd --toggle-switcher` command, we get de-activation of skippy.

2. If I set up Alt+Tab to do `skippy-xd --activate-switcher` command, somehow the `ps->o.focus_initial == FI_NEXT` code is not set, and the window always focuses on the first window.

3. If I set up Alt+Tab to triggers a `skippy-xd --next` command, the window still always focuses on the *second* window, however many times I press 'tab'.

@dreamcat4 probably I messed up the code somewhere, probably #101 or others?

**Comment by dreamcat4** [comment]
Hey felix!
Yes so (yet again) I am quite unable to dedicate the amount of time this project deserves. To do a justicy :)

However my guy feeling here is that the following algorithm might be most effecient:

* Starting from my current position here, then all of the way to HEAD, we generate a list of commits. Corresponding to the MERGE end commit. (so that might be fewer steps in the list).
* Do a git bisect based on those PR level points in the git history.
* Narrow it down that way.


I don't really have an opinion, until after doing that. And perhaps might stumble upon find other thing(s) could be broken. And to see how far into these PRs it goes....

Hopefully this is a good enough strategy. To then give a clearer feedback. So sorry I cannot just jump on this immediately. As am right in the middle of some other tasks right now... which are themselves quite time consuming things. My focus is very distracted away into other different areas. But I hope to give it a shot later in, hoping to find a bit of time during the next week or 2.
