### ISSUE TITLE
Tooltip bug when followsMouse=true

### ISSUE THREAD

**Issue by felixfung** [dreamcat4/skippy-xd#137]
With PR #136, we got good behaviour when tooltip config option followsMouse=false. However, we introduced bug when followsMouse=true, according to this table:

movePointer | followsMouse | starting | keysNext | keysPrev | FocusIn | FocusOut | MotionNotify
-- | -- | -- | -- | -- | -- | -- | -- |
true | true | BUG | BUG | BUG
true | false |
false | true | BUG | BUG | BUG
false | false |

**Comment by felixfung** [comment]
Looks like the root cause of the bug (which was at least partly there before #136) was due to the mouse coordinates being relative to the "root window", which depends on different factors during different states. So far I have not figured it out, and I always have bad experience dealing with x11...

I am inclined to remove the tooltip followsMouse option, so that tooltip always shows below window thumbnails, and is already bug free.

I personally quite prefer it showing on the bottom, but then I don't even use tooltip...

Any feedback is welcomed.

**Comment by dreamcat4** [comment]
Hello felix,
When i was hacking by myself (on my own personal fork, never committed, which totally got broken, and is never coming back): I also indeed encountered such very similar looking tooltip bug. And then turned out was difficult to debug / find / fix. Never found a fix for it either.

So **yes**:

to be putting the window text / title beneath each thumbnails. Well I certainly also prefer too. Totally agree / support this decision. +1 for this
