### ISSUE TITLE
How is this project going to go forward?

### ISSUE THREAD

**Issue by felixfung** [dreamcat4/skippy-xd#40]
Recently I made contributions to skippy-xd, to add animation, improve window lay out to resemble the original window positioning, and fixed some bugs. I also pointed out some ways to improve alt-tab usage and implement visualization of minimized windows, among other possibilities of improvement.

@dreamcat4 has been kind enough to encourage me to work on, and take on this project. I have received no feedback from anyone else. Right now personally 95% of my itch on this project is scratched.

I believe in open source projects and contribution, and I believe there are many fans of expose-like feature in the Linux world, even after excluding those in the GNOME and KDE world. I myself was hunting for this feature in vain for many years, until I decided to step up and do some coding myself. Hence, I would be happy to continue to contribute to skippy-xd. However, I cannot do this alone. At the absolute bare minimum, I need feedback that there are people who value this work, and that there are people who are willing to do testing. And then, that it eventually gets packaged in different distros :)

**Comment by dreamcat4** [comment]
my overall feelings about the worth, and future value of this project:

well in my opinion, the code itself is a rat's nest, and rather prone to bugs and such. however it is really cool project and really can be a lot of fun to hack on.

in terms of the practical value to others, and continued direct usage. i feel it's great for anybody on xorg/x11. but clearly since this app is so coded to work only on x then it kindda is like a legacy app. with no prospects for adding wayland support. because that would require a complete rewrite from scratch.

however when i am in a wayland session, skippy will still work fine to iterate over any xapps that are running under xwayland. it just cannot include wayland native apps... so it still (while being legacy) can be invoked and used in that sense.

anyhow lets say that all dies away over time, as more of the users gradually (inevitably) move over from x to wayland. year on year. in this situation then skippy still is of a broader appeal as an example to others. for how to do things right. because skippy provides a lot of user configurable options, can be used both as expose and alt+tab. and just makes sensible choices in design and features set than makes a lot of sense. it can satisfy the tastes of a lot of different users. who each prefer different specific set of (combination of) settings / behaviours.

so all in all, when i look at what is being implemented natively for wayland. for example in kde, gnome and sway / wlroots (and a few other recent modern active de like budgie and popos' 'cosmic')... 

a lot of those others will implement some very kiss style or opinionated sub-set of feature(s). which is less configurable or customizable than skippy. so having skippy exist out there as a shining example can still be a good reference for future developers. who want to re-implement again. to redo for wayland... as must be! since skippy is really xorg only, it cannot be refactored to support wayland itself. less effort to start from scratch.

but until then, we can still enjoy what skippy has to offer. and can be fun to code, sort of easy going project to work on.

to finish / wrap up:

do hope this issue will help attract future contributors. or existing users to comment, and say how they feel towards future direction for this project, all the best

**Comment by felixfung** [comment]
Wayland is taking over? Honestly I have not been following news in the Linux ecosystem for so long... I hope X still has at least a few years? Then this project would be worthwhile. The code is workable, I was able to extend the features in a matter of weeks, and see likewise for other tasks.

**Comment by dreamcat4** [comment]
yes to both, there is still significant years  and users will remain on x. but also wayland is taking over too, so no worries. both are true

**Comment by vredesbyyrd** [comment]
Speaking as user, I was very happy to see skippy-xd continue to get some much deserved love. I'm testing your latest work and will continue to do so. The animation you implemented look and function great, very impressive! 

Regarding the value of this tool being X only - you browse any linux forum, reddit etc..._my_ impression is a lot of people are still choosing to use x or have not been able to switch to wayland for a number of reasons. Personally, I cannot switch to wayland until its fully color managed, and last I checked that's still a waaays off. 

> yes to both, there is still significant years and users will remain on x. but also wayland is taking over too, so no worries. both are true

Well put, in full agreement. 

Generally speaking, a lightweight wm independent overview mode is a great idea imho. Its kept me from having to be tied into gnome or kde (both great projects, just not for me).

I'm personally very interested in #36, and wish I had the smarts to work on it myself but I am not a programmer - shell scripts, python etc wreck my brain enough. 

At the least, I will brainstorm some ways to get some eyeballs on skippy for people who may not know it exists, and i'll continue to test changes / report bugs.

**Comment by felixfung** [comment]
@vredesbyyrd wondering if you have tested the "boxy" layout?

**Comment by vredesbyyrd** [comment]
I have not yet. I should have time tomorrow to build / test it. I'll report back. Thanks for the heads up.
