### ISSUE TITLE
black boxes - for multiple virtual desktops (kde plasma 5.27+ xorg)

### ISSUE THREAD

**Issue by dreamcat4** [dreamcat4/skippy-xd#65]
example video

https://drive.google.com/file/d/1y4cgYjXz904Cyh9WyI3pf_wSgPL91S0_/view?usp=sharing

what i am observing here on kde is that the black windows are mapping exactly to all windows not on the current virtual desktop. (so on all other virtual desktops)

#### example

lets say there are total 10 windows open in kde. spread across 4 different virtual desktops.

now i am switched to virtual desktop '2'. and it has 3 open windows. then i invoke `skippy-xd --next`.

skippy loads. does some things. then eventually mainwin gets initially drawn (for first time). but the clienwin thumbnail images are only being displayed for the virtual desktop i am currently in. which is desktop '2'. so 3 windows are shown. and the remaining 7/10 windows there is a clientwin box drawn. and all in correct layout. but it is filled black color / blank.

however if i advance the selection further. or hoever the mouse over any blank windows.... then the thumbnails appears on hover / on highlighting them.

as the mouse leaves the clientwin hover zone. (or is advanced by keyboard navigation to select the next clientwin). then the un-hover thumbnail turns black once more. until the mouse goes back to it.

2) i can exist skippy. and move from virtual desktop 2 ---> a differnt virtual desktop (3). then a different set of windows will be appearing for the now current dektop 3. and all of the others starts blank.

in this example, none of the windows are minimized state or iconified state. they are all open windows (restored state, visible). however not all of them are located on the current virtual desktop.

for any windows which are set to always show across 'all of desktops' - these are displayed always in skippy too. so are being treated same way as those within the currently selected desktop.

### when was this first observed?

right after merging the iconify windows / thumbnails pr.

### what was behaviour before that?

it was that the blank windows instead were filled a white color. showing a small application icon. so in this sense this bug seems to have existed before the pr was merged. what has changed now afterward the color is now black instead. and not visible the applications icon anymore.

### can this be fixed?

hope this can be fixed because clearly the manual user action of moving the mouse to enter the clientwin zone then paints the thumbnail into the box. and this is without switching virtual desktops.

so either skippy made the thumbnail already during startup time (already is there and just didnt display it initially). or otherwise it make request on mouse entering a clientwin zone

**Comment by felixfung** [comment]
Most probably KDE unmaps windows not in the current virtual desktop. Still, there is some unintended behaviour going on...

When a window is not mapped, there are 2.5 possibilities:
1. The window was never mapped before skippy daemon started. Then, the window is in filled or icon state, so that a rectangle (colour depends on config) and when applicable icon is shown rather than thumbnail.
2. The window has been mapped at some point when skippy daemon was on. Then it would go into zombie mode, and the last mapped image would be shown.
2.5. Unintended behaviour: sometimes a window should go into zombie mode but stays in filled/icon mode. My guess is due to the bad match/bad pixmap errors #52. I am guessing it #54 has the same root cause.

So it looks like for your case, you get scenario 2.5 all the time.

In addition, for you the filled colour changes from white to black...

What if you add to your config file this:
[shadow]
tint = #111111
tintOpacity = 120
opacity = 160

**Comment by dreamcat4** [comment]
ah ok i see now... felix - it is a simple matter to rectify. I will push up fix sometime today

this will be great to use skippy again. to be on master (working well) and then can try out those other modes etc. more easily. for those other stuff

Just gotta do this one first

**Comment by dreamcat4** [comment]
@felixfung if you check the above commit ^^ here... there is a section in `skippy.h`. This is the place to add C defaults for options. You missed it when adding those new setting during the iconify previews PR. Have pushed now the fix.
